
    export const table = [
      "Patient", "Consulting Doctor", "Appointment Date", "Appointment Time", "Reason", "Practice", "Organization", "Action"
    ];



    export const initialData = [
      {
        id: 1,
        patient: "John Doe",
        consultingDoctor: "Dr. Smith",
        dateOfAppointment: "2024-08-30",
        timeOfAppointment: "09:00 AM",
        reason: "Annual Check-up",
        practice: "Internal Medicine",
        organization: "Health Clinic",
      },
      {
        id: 2,
        patient: "Jane Doe",
        consultingDoctor: "Dr. Lee",
        dateOfAppointment: "2024-08-31",
        timeOfAppointment: "10:00 AM",
        reason: "Follow-up",
        practice: "Cardiology",
        organization: "HeartCare Center",
      },
      {
        id: 3,
        patient: "Alice Johnson",
        consultingDoctor: "Dr. Brown",
        dateOfAppointment: "2024-09-01",
        timeOfAppointment: "11:00 AM",
        reason: "Blood Test Review",
        practice: "General Practice",
        organization: "MedCare Clinic",
      },
      {
        id: 4,
        patient: "Bob Williams",
        consultingDoctor: "Dr. Clark",
        dateOfAppointment: "2024-09-02",
        timeOfAppointment: "01:00 PM",
        reason: "Routine Check-up",
        practice: "Pediatrics",
        organization: "Kids Health",
      },
      {
        id: 5,
        patient: "Carol Evans",
        consultingDoctor: "Dr. Patel",
        dateOfAppointment: "2024-09-03",
        timeOfAppointment: "02:00 PM",
        reason: "Consultation",
        practice: "Dermatology",
        organization: "Skin Health",
      },
      {
        id: 6,
        patient: "Dave Miller",
        consultingDoctor: "Dr. Davis",
        dateOfAppointment: "2024-09-04",
        timeOfAppointment: "03:00 PM",
        reason: "Physical Therapy",
        practice: "Rehabilitation",
        organization: "MoveWell Center",
      },
      {
        id: 7,
        patient: "Emma Thompson",
        consultingDoctor: "Dr. Scott",
        dateOfAppointment: "2024-09-05",
        timeOfAppointment: "04:00 PM",
        reason: "Specialist Consultation",
        practice: "Neurology",
        organization: "Brain Health",
      },
      {
        id: 8,
        patient: "Frank Garcia",
        consultingDoctor: "Dr. Martin",
        dateOfAppointment: "2024-09-06",
        timeOfAppointment: "09:30 AM",
        reason: "Allergy Testing",
        practice: "Allergy Clinic",
        organization: "Allergy Experts",
      },
      {
        id: 9,
        patient: "Grace Martinez",
        consultingDoctor: "Dr. Lee",
        dateOfAppointment: "2024-09-07",
        timeOfAppointment: "10:30 AM",
        reason: "Preventive Care",
        practice: "Family Medicine",
        organization: "Wellness Center",
      },
      {
        id: 10,
        patient: "Henry Wilson",
        consultingDoctor: "Dr. White",
        dateOfAppointment: "2024-09-08",
        timeOfAppointment: "11:30 AM",
        reason: "Eye Examination",
        practice: "Ophthalmology",
        organization: "Vision Clinic",
      },
      {
        id: 11,
        patient: "Irene Davis",
        consultingDoctor: "Dr. Lewis",
        dateOfAppointment: "2024-09-09",
        timeOfAppointment: "01:30 PM",
        reason: "Cardiac Check",
        practice: "Cardiology",
        organization: "HeartCare Center",
      },
      {
        id: 12,
        patient: "Jack Taylor",
        consultingDoctor: "Dr. Walker",
        dateOfAppointment: "2024-09-10",
        timeOfAppointment: "02:30 PM",
        reason: "Diabetes Management",
        practice: "Endocrinology",
        organization: "Diabetes Clinic",
      },
      {
        id: 13,
        patient: "Kelly Anderson",
        consultingDoctor: "Dr. Hall",
        dateOfAppointment: "2024-09-11",
        timeOfAppointment: "03:30 PM",
        reason: "Chronic Illness Review",
        practice: "Internal Medicine",
        organization: "Health Clinic",
      },
      {
        id: 14,
        patient: "Liam Jackson",
        consultingDoctor: "Dr. Adams",
        dateOfAppointment: "2024-09-12",
        timeOfAppointment: "04:30 PM",
        reason: "Orthopedic Consultation",
        practice: "Orthopedics",
        organization: "Bone Health",
      },
      {
        id: 15,
        patient: "Mia Roberts",
        consultingDoctor: "Dr. Taylor",
        dateOfAppointment: "2024-09-13",
        timeOfAppointment: "09:00 AM",
        reason: "Mental Health Support",
        practice: "Psychiatry",
        organization: "MindCare Center",
      }
    ];
